# Generated by Django 5.2 on 2025-04-08 10:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('encrypted_secret', models.BinaryField()),
                ('public_key', models.BinaryField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('param_type', models.CharField(choices=[('INT', 'Integer'), ('STR', 'String'), ('BOOL', 'Boolean'), ('JSON', 'JSON')], max_length=4)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Parameter',
                'verbose_name_plural': 'System Parameters',
                'db_table': 'system_parameters',
            },
        ),
        migrations.CreateModel(
            name='SessionKey',
            fields=[
                ('key_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_sessions', to='core.client')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responded_sessions', to='core.client')),
            ],
            options={
                'verbose_name': 'Session Key',
                'verbose_name_plural': 'Session Keys',
                'db_table': 'session_keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConnectionLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('connection_type', models.CharField(choices=[('KDC', 'KDC Authentication'), ('P2P', 'Peer-to-Peer'), ('REG', 'Registration'), ('AUTH', 'Authorization'), ('KEY', 'Key Exchange')], max_length=4)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], max_length=7)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('initiator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_connections', to='core.client')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_connections', to='core.client')),
                ('session_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sessionkey')),
            ],
            options={
                'verbose_name': 'Connection Log',
                'verbose_name_plural': 'Connection Logs',
                'db_table': 'connection_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('authorized_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_authorizations', to='core.client')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_authorizations', to='core.client')),
            ],
            options={
                'verbose_name': 'Authorization',
                'verbose_name_plural': 'Authorizations',
                'db_table': 'authorizations',
                'unique_together': {('client', 'authorized_client')},
            },
        ),
    ]
