# Generated by Django 5.2 on 2025-05-07 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=100)),
                ('secret_id', models.BinaryField()),
                ('authorized_peers', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField()),
                ('public_key', models.BinaryField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('AUTH', 'Authentication'), ('CONN', 'Connection'), ('PSK', 'Key Exchange'), ('REG', 'Registration'), ('ERR', 'Error')], max_length=4)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.client')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('EXPIRATION', 'Identity Expiration'), ('NEW_PEER', 'New Peer Authorization'), ('PSK_UPDATE', 'PSK Updated'), ('SYSTEM', 'System Message')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_url', models.CharField(blank=True, max_length=200, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.client')),
            ],
        ),
        migrations.CreateModel(
            name='SessionKey',
            fields=[
                ('session_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('session_key', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.client')),
            ],
        ),
        migrations.CreateModel(
            name='PSKExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_psk', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_psks', to='dashboard.client')),
                ('to_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_psks', to='dashboard.client')),
            ],
            options={
                'unique_together': {('from_client', 'to_client')},
            },
        ),
    ]
