# Generated by Django 5.2 on 2025-05-07 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='custom_client_table',
        ),
    ]
