# Generated by Django 5.2 on 2025-05-07 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_client_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='client',
        ),
        migrations.AlterModelTable(
            name='clientlog',
            table='client_logs',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='notifications',
        ),
        migrations.AlterModelTable(
            name='pskexchange',
            table='psk_exchange',
        ),
        migrations.AlterModelTable(
            name='sessionkey',
            table='session_keys',
        ),
    ]
