# Generated by Django 5.2 on 2025-05-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_client_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
